name: "ğŸï¸ Â» setup environment"
description: "setup all necessary tools for the workflow to run"
inputs:
  python-version:  
    description: "Version of python to install"
    required: true

defaults:
  run:
    shell: 'bash'

runs:
  using: "composite"

  steps:
    - name: ğŸï¸ Â» setup environment
      shell: bash
      run: echo "ğŸï¸ Â» setup environment with python ${{inputs.python-version}}"

    - name: ğŸ§Š Â» install go-task
      uses: arduino/setup-task@v1
      with:
        version: 3.x

    - name: ğŸ¦€ Â» install rust
      uses: dtolnay/rust-toolchain@stable

    - name: ğŸ“œ Â» log sysinfo
      shell: bash
      run: |
        uname -a
        task --version
        cargo --version
        rustc --version
        rustup --version