name: "âœ… Â» checks"

on:
  workflow_call:

defaults:
  run:
    shell: 'bash'

jobs:
  check:
    name: "âœ… Â» check"
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“ Â» checkout repository
        uses: actions/checkout@v6

      - name: ğŸ¦€ Â» install stable rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: ğŸ¦€ Â» install nightly rust (for rustfmt)
        uses: dtolnay/rust-toolchain@nightly
        with:
            components: rustfmt

      - name: ğŸ—ƒï¸ Â» cache cargo
        uses: Swatinem/rust-cache@v2
     
      - name: ğŸ§Š Â» install Task
        uses: go-task/setup-task@v1
        with:
          version: 3.x

      - name: ğŸ—ï¸ Â» build kurv
        run: task build

      - name: ğŸ§ª Â» test kurv
        run: cargo test
      
      - name: ğŸ•µï¸ Â» check lint & format
        run: task check
